// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMe6hh_eZEc5_EYlWIsebLcAlMJbgPuKY',
    appId: '1:660345122160:web:0e57c1bd7662a6cf7673b5',
    messagingSenderId: '660345122160',
    projectId: 'pride-of-knowledge',
    authDomain: 'pride-of-knowledge.firebaseapp.com',
    storageBucket: 'pride-of-knowledge.appspot.com',
    measurementId: 'G-Y37NBCXRSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTI-dK-S17CO0ar4OCbGqNwhDFo5hIWwk',
    appId: '1:660345122160:android:1b8d22f71a05dcac7673b5',
    messagingSenderId: '660345122160',
    projectId: 'pride-of-knowledge',
    storageBucket: 'pride-of-knowledge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd8xe7r7nQ8sBIRrt-4NMkPEDBZdfWZzU',
    appId: '1:660345122160:ios:444c9a5fb311dd6c7673b5',
    messagingSenderId: '660345122160',
    projectId: 'pride-of-knowledge',
    storageBucket: 'pride-of-knowledge.appspot.com',
    iosBundleId: 'com.example.prideofknowledge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd8xe7r7nQ8sBIRrt-4NMkPEDBZdfWZzU',
    appId: '1:660345122160:ios:444c9a5fb311dd6c7673b5',
    messagingSenderId: '660345122160',
    projectId: 'pride-of-knowledge',
    storageBucket: 'pride-of-knowledge.appspot.com',
    iosBundleId: 'com.example.prideofknowledge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMe6hh_eZEc5_EYlWIsebLcAlMJbgPuKY',
    appId: '1:660345122160:web:dc52019cf72e71eb7673b5',
    messagingSenderId: '660345122160',
    projectId: 'pride-of-knowledge',
    authDomain: 'pride-of-knowledge.firebaseapp.com',
    storageBucket: 'pride-of-knowledge.appspot.com',
    measurementId: 'G-HEJ6BY8J3T',
  );
}
